#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectDir = path.dirname(scriptDir);
const dataDir = path.join(projectDir, "data");
const outputPath = path.join(projectDir, "extra-games.js");
const chunkNames = ["extra-games-a.json", "extra-games-b.json", "extra-games-c.json"];

const chunks = chunkNames.map((name) => {
  const filePath = path.join(dataDir, name);
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
});
const games = Object.assign({}, ...chunks);
const keys = Object.keys(games);
const expectedKeys = Array.from(
  { length: 93 },
  (_, index) => `extra${String(index + 1).padStart(3, "0")}`,
);

if (JSON.stringify(keys) !== JSON.stringify(expectedKeys)) {
  throw new Error("Expected continuous extra001-extra093 game keys");
}

let roundCount = 0;
for (const [key, game] of Object.entries(games)) {
  if (!Array.isArray(game.rounds) || game.rounds.length !== 3) {
    throw new Error(`${key}: expected exactly three rounds`);
  }
  roundCount += game.rounds.length;
  for (const [index, round] of game.rounds.entries()) {
    if (!Array.isArray(round.options) || round.options.length !== 3) {
      throw new Error(`${key}/round${index + 1}: expected exactly three options`);
    }
    if (round.options.filter((option) => option.correct === true).length !== 1) {
      throw new Error(`${key}/round${index + 1}: expected exactly one correct option`);
    }
  }
}

const content = `/* Generated by scripts/build_extra_games.mjs. Do not edit by hand. */
window.MONGLE_EXTRA_GAMES = Object.freeze(
${JSON.stringify(games, null, 2)}
);
window.MONGLE_EXTRA_META = Object.freeze({ gameCount: ${keys.length}, roundCount: ${roundCount} });
`;

const temporaryPath = `${outputPath}.tmp`;
fs.writeFileSync(temporaryPath, content, "utf8");
fs.renameSync(temporaryPath, outputPath);
console.log(`Built ${outputPath}: ${keys.length} games, ${roundCount} rounds.`);
